const existingAssets = [
  "GBASnowLand",
  "DSShroomRidge",
  "DSPeachGardens",
  "WiiDryDryRuins",
  "GBALuigiCircuit",
  "GBAYoshiDesert",
  "GCNMushroomBridge",
  "GCNMushroomCity",
  "GCNWaluigiStadium",
  "TourAT",
  "TourBR",
  "TourDarkKingdom",
  "TourMA",
  "TourMU",
  "TourNU",
  "TourOR",
  "TourYI",
];
export default existingAssets;
